import { NextResponse } from "next/server"

export const runtime = "nodejs"

/**
 * GET /api/menu/structure - Get complete menu structure with categories and products
 */
export async function GET() {
  const headers = { "Content-Type": "application/json" }

  try {
    console.log("🔍 [/api/menu/structure] Fetching menu structure...")

    // Return mock data structure for now
    const mockMenuStructure = {
      main_categories: [
        {
          id: "1",
          name: "Beverages",
          description: "All drink items including coffee, tea, and specialty beverages",
          icon: "Coffee",
          display_order: 1,
          is_active: true,
          subcategories: [
            {
              id: "1",
              name: "Espresso",
              description: "Classic espresso-based drinks",
              main_category_id: "1",
              display_order: 1,
              is_active: true,
              products: [
                {
                  id: "1",
                  name: "Classic Espresso",
                  description: "Rich, bold espresso shot with perfect crema",
                  price: 89,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "1",
                  is_active: true,
                  is_featured: true,
                  rating: 4.8,
                  prep_time: 2,
                  stock_quantity: 100,
                  tags: ["coffee", "espresso", "hot"],
                },
                {
                  id: "2",
                  name: "Americano",
                  description: "Espresso with hot water for a clean, strong taste",
                  price: 95,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "1",
                  is_active: true,
                  is_featured: false,
                  rating: 4.6,
                  prep_time: 2,
                  stock_quantity: 100,
                  tags: ["coffee", "espresso", "hot"],
                },
                {
                  id: "3",
                  name: "Cappuccino",
                  description: "Espresso with steamed milk and thick foam",
                  price: 115,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "1",
                  is_active: true,
                  is_featured: true,
                  rating: 4.7,
                  prep_time: 3,
                  stock_quantity: 100,
                  tags: ["coffee", "espresso", "milk", "hot"],
                },
                {
                  id: "4",
                  name: "Latte",
                  description: "Smooth espresso with steamed milk",
                  price: 125,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "1",
                  is_active: true,
                  is_featured: true,
                  rating: 4.8,
                  prep_time: 3,
                  stock_quantity: 100,
                  tags: ["coffee", "espresso", "milk", "hot"],
                },
              ],
            },
            {
              id: "2",
              name: "Signature",
              description: "House specialty beverages",
              main_category_id: "1",
              display_order: 2,
              is_active: true,
              products: [
                {
                  id: "5",
                  name: "Sol Signature Blend",
                  description: "Our house special coffee blend",
                  price: 135,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "2",
                  is_active: true,
                  is_featured: true,
                  rating: 4.9,
                  prep_time: 4,
                  stock_quantity: 100,
                  tags: ["coffee", "signature", "hot"],
                },
                {
                  id: "6",
                  name: "Caramel Macchiato",
                  description: "Espresso with vanilla and caramel",
                  price: 145,
                  image_url: "/menu-espresso-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "2",
                  is_active: true,
                  is_featured: true,
                  rating: 4.7,
                  prep_time: 4,
                  stock_quantity: 100,
                  tags: ["coffee", "caramel", "sweet", "hot"],
                },
              ],
            },
            {
              id: "3",
              name: "Matcha",
              description: "Matcha-based drinks and lattes",
              main_category_id: "1",
              display_order: 3,
              is_active: true,
              products: [
                {
                  id: "7",
                  name: "Matcha Latte",
                  description: "Premium matcha with steamed milk",
                  price: 135,
                  image_url: "/menu-matcha-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "3",
                  is_active: true,
                  is_featured: true,
                  rating: 4.6,
                  prep_time: 3,
                  stock_quantity: 100,
                  tags: ["matcha", "tea", "milk", "hot"],
                },
                {
                  id: "8",
                  name: "Iced Matcha",
                  description: "Refreshing cold matcha drink",
                  price: 125,
                  image_url: "/menu-matcha-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "3",
                  is_active: true,
                  is_featured: false,
                  rating: 4.5,
                  prep_time: 2,
                  stock_quantity: 100,
                  tags: ["matcha", "tea", "cold", "iced"],
                },
              ],
            },
            {
              id: "6",
              name: "Coffee Frappe",
              description: "Coffee-based blended drinks",
              main_category_id: "1",
              display_order: 6,
              is_active: true,
              products: [
                {
                  id: "9",
                  name: "Classic Coffee Frappe",
                  description: "Blended coffee with ice and cream",
                  price: 155,
                  image_url: "/menu-frappucino-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "6",
                  is_active: true,
                  is_featured: true,
                  rating: 4.8,
                  prep_time: 5,
                  stock_quantity: 100,
                  tags: ["coffee", "frappe", "cold", "blended"],
                },
                {
                  id: "10",
                  name: "Mocha Frappe",
                  description: "Chocolate coffee frappe with whipped cream",
                  price: 165,
                  image_url: "/menu-frappucino-updated.jpg",
                  main_category_id: "1",
                  subcategory_id: "6",
                  is_active: true,
                  is_featured: true,
                  rating: 4.7,
                  prep_time: 5,
                  stock_quantity: 100,
                  tags: ["coffee", "chocolate", "frappe", "cold"],
                },
              ],
            },
          ],
        },
        {
          id: "2",
          name: "Food",
          description: "Food items including waffles, burgers, and other meals",
          icon: "UtensilsCrossed",
          display_order: 2,
          is_active: true,
          subcategories: [
            {
              id: "7",
              name: "Waffle",
              description: "Belgian waffles and waffle-based dishes",
              main_category_id: "2",
              display_order: 1,
              is_active: true,
              products: [
                {
                  id: "11",
                  name: "Classic Belgian Waffle",
                  description: "Crispy waffle with butter and syrup",
                  price: 185,
                  image_url: "/placeholder.svg?height=300&width=200&text=Waffle",
                  main_category_id: "2",
                  subcategory_id: "7",
                  is_active: true,
                  is_featured: true,
                  rating: 4.6,
                  prep_time: 8,
                  stock_quantity: 50,
                  tags: ["waffle", "breakfast", "sweet"],
                },
                {
                  id: "12",
                  name: "Chocolate Waffle",
                  description: "Waffle with chocolate chips and sauce",
                  price: 215,
                  image_url: "/placeholder.svg?height=300&width=200&text=Choco+Waffle",
                  main_category_id: "2",
                  subcategory_id: "7",
                  is_active: true,
                  is_featured: true,
                  rating: 4.7,
                  prep_time: 8,
                  stock_quantity: 50,
                  tags: ["waffle", "chocolate", "sweet"],
                },
              ],
            },
            {
              id: "10",
              name: "Burger",
              description: "Gourmet burgers and sandwiches",
              main_category_id: "2",
              display_order: 4,
              is_active: true,
              products: [
                {
                  id: "13",
                  name: "Sol Beef Burger",
                  description: "Juicy beef patty with fresh vegetables",
                  price: 285,
                  image_url: "/placeholder.svg?height=300&width=200&text=Burger",
                  main_category_id: "2",
                  subcategory_id: "10",
                  is_active: true,
                  is_featured: true,
                  rating: 4.8,
                  prep_time: 12,
                  stock_quantity: 30,
                  tags: ["burger", "beef", "lunch"],
                },
                {
                  id: "14",
                  name: "Chicken Burger",
                  description: "Grilled chicken breast with special sauce",
                  price: 265,
                  image_url: "/placeholder.svg?height=300&width=200&text=Chicken+Burger",
                  main_category_id: "2",
                  subcategory_id: "10",
                  is_active: true,
                  is_featured: false,
                  rating: 4.6,
                  prep_time: 12,
                  stock_quantity: 30,
                  tags: ["burger", "chicken", "lunch"],
                },
              ],
            },
          ],
        },
      ],
      variations: [
        { id: "1", name: "Small", type: "size", price_modifier: -15, is_active: true },
        { id: "2", name: "Medium", type: "size", price_modifier: 0, is_active: true },
        { id: "3", name: "Large", type: "size", price_modifier: 20, is_active: true },
        { id: "4", name: "Hot", type: "temperature", price_modifier: 0, is_active: true },
        { id: "5", name: "Iced", type: "temperature", price_modifier: 5, is_active: true },
      ],
      add_ons: [
        {
          id: "1",
          name: "Extra Shot",
          description: "Additional espresso shot",
          price: 15,
          category: "coffee",
          max_quantity: 3,
          is_active: true,
        },
        {
          id: "2",
          name: "Vanilla Syrup",
          description: "Sweet vanilla flavoring",
          price: 10,
          category: "syrup",
          max_quantity: 2,
          is_active: true,
        },
        {
          id: "3",
          name: "Caramel Syrup",
          description: "Rich caramel flavoring",
          price: 10,
          category: "syrup",
          max_quantity: 2,
          is_active: true,
        },
        {
          id: "4",
          name: "Oat Milk",
          description: "Plant-based oat milk",
          price: 15,
          category: "milk",
          max_quantity: 1,
          is_active: true,
        },
        {
          id: "5",
          name: "Whipped Cream",
          description: "Fresh whipped cream topping",
          price: 15,
          category: "topping",
          max_quantity: 1,
          is_active: true,
        },
      ],
    }

    console.log("✅ Successfully returning menu structure")

    return NextResponse.json(
      {
        data: mockMenuStructure,
        source: "mock",
        message: "Menu structure loaded successfully",
        timestamp: new Date().toISOString(),
      },
      { headers, status: 200 },
    )
  } catch (err) {
    console.error("❌ [/api/menu/structure] Error:", err)

    return NextResponse.json(
      {
        error: err instanceof Error ? err.message : "Failed to load menu structure",
        timestamp: new Date().toISOString(),
      },
      { headers, status: 500 },
    )
  }
}
